[package]
name = "wallcord"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
image = "0.25.6"
reqwest = {version = "0.12.23", features = ["blocking"]}
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.142"
threadpool = "1.8.1"
